# Generated by Django 5.2.17 on 2026-09-29 16:19

import django.db.models.deletion
import measurements.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementPlan',
            fields=[
                ('id', models.CharField(default=measurements.models.measurement_id, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('scope', models.TextField()),
                ('lead_surveyor', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('in-progress', 'in-progress'), ('reconciled', 'reconciled'), ('cancelled', 'cancelled')], default='scheduled', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_measurement_plans', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_plans', to='organizations.organization')),
                ('vessel_call', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_plans', to='operations.vesselcall')),
            ],
            options={
                'ordering': ('-scheduled_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MeasurementEvidence',
            fields=[
                ('id', models.CharField(default=measurements.models.measurement_id, max_length=32, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=1024, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_evidence_uploads', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='measurements.measurementplan')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CargoLine',
            fields=[
                ('id', models.CharField(default=measurements.models.measurement_id, max_length=32, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=100)),
                ('container_size', models.CharField(blank=True, max_length=20)),
                ('load_status', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(choices=[('tonnes', 'tonnes'), ('count', 'count'), ('m3', 'm3')], max_length=20)),
                ('basis', models.CharField(max_length=255)),
                ('manifest_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('baseline_reference', models.CharField(blank=True, max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='measurements.measurementplan')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.CharField(default=measurements.models.measurement_id, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('representative', models.CharField(blank=True, max_length=255)),
                ('required_submission', models.BooleanField(default=True)),
                ('required_approval', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='measurements.measurementplan')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='MeasurementSubmission',
            fields=[
                ('id', models.CharField(default=measurements.models.measurement_id, max_length=32, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('observed_at', models.DateTimeField()),
                ('source_reference', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ManyToManyField(related_name='submissions', to='measurements.measurementevidence')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='measurements.measurementplan')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_submissions', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='measurements.participant')),
            ],
            options={
                'ordering': ('recorded_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.CharField(default=measurements.models.measurement_id, max_length=32, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('final', 'final'), ('superseded', 'superseded')], default='draft', max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(null=True)),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ManyToManyField(related_name='reconciliations', to='measurements.measurementevidence')),
                ('finalized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='measurements.measurementplan')),
                ('submissions', models.ManyToManyField(related_name='reconciliations', to='measurements.measurementsubmission')),
            ],
            options={
                'ordering': ('revision',),
            },
        ),
        migrations.CreateModel(
            name='DisparityAssessment',
            fields=[
                ('id', models.CharField(default=measurements.models.measurement_id, max_length=32, primary_key=True, serialize=False)),
                ('payer', models.CharField(max_length=255)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('policy', models.CharField(choices=[('manifest-disparity', 'manifest-disparity'), ('quantity-adjustment', 'quantity-adjustment')], max_length=30)),
                ('tariff_reference', models.CharField(max_length=255)),
                ('opening_charges_reference', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('ready', 'ready'), ('no-charge', 'no-charge'), ('held', 'held'), ('issued', 'issued')], max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disparity_assessments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='measurements.measurementplan')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='measurements.reconciliation')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReconciliationApproval',
            fields=[
                ('id', models.CharField(default=measurements.models.measurement_id, max_length=32, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('agreed', 'agreed'), ('disputed', 'disputed')], max_length=20)),
                ('representative', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ManyToManyField(related_name='approvals', to='measurements.measurementevidence')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measurements.participant')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='measurements.reconciliation')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_reconciliation_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('recorded_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReconciliationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('manifest_quantity', models.DecimalField(decimal_places=3, max_digits=18, null=True)),
                ('variance', models.DecimalField(decimal_places=3, max_digits=19, null=True)),
                ('reason', models.TextField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measurements.cargoline')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='measurements.reconciliation')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reported', 'reported'), ('not-applicable', 'not-applicable')], max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('note', models.TextField(blank=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measurements.cargoline')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='measurements.measurementsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=20)),
                ('baseline_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('final_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('variance', models.DecimalField(decimal_places=3, max_digits=19)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tolerance', models.DecimalField(decimal_places=3, max_digits=18)),
                ('tolerance_mode', models.CharField(max_length=20)),
                ('chargeable_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('entitlement', models.DecimalField(decimal_places=2, max_digits=18)),
                ('opening_billed_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('prior_invoiced_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measurements.cargoline')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='measurements.disparityassessment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assessment', 'line'), name='measurement_unique_assessed_line')],
            },
        ),
        migrations.AddConstraint(
            model_name='cargoline',
            constraint=models.CheckConstraint(condition=models.Q(('manifest_quantity__gte', 0), ('manifest_quantity__isnull', True), _connector='OR'), name='measurement_manifest_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='measurementsubmission',
            constraint=models.UniqueConstraint(fields=('participant', 'revision'), name='measurement_unique_submission_revision'),
        ),
        migrations.AddConstraint(
            model_name='reconciliation',
            constraint=models.UniqueConstraint(fields=('plan', 'revision'), name='measurement_unique_reconciliation_revision'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationline',
            constraint=models.UniqueConstraint(fields=('reconciliation', 'line'), name='measurement_unique_reconciled_line'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='measurement_final_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='submissionline',
            constraint=models.UniqueConstraint(fields=('submission', 'line'), name='measurement_unique_return_line'),
        ),
        migrations.AddConstraint(
            model_name='submissionline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity__gte', 0), ('status', 'reported')), models.Q(('quantity__isnull', True), ('status', 'not-applicable')), _connector='OR'), name='measurement_valid_return_quantity'),
        ),
    ]
