# Generated by Django 5.2.17 on 2026-09-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submissionline',
            name='measurement_valid_return_quantity',
        ),
        migrations.AddConstraint(
            model_name='submissionline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity__gte', 0), ('quantity__isnull', False), ('status', 'reported')), models.Q(('quantity__isnull', True), ('status', 'not-applicable')), _connector='OR'), name='measurement_valid_return_quantity'),
        ),
    ]
