# Generated by Django 5.2.16 on 2026-07-26
import accounts.managers
import accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizations", "0001_initial"),
    ]
    operations = [
        migrations.CreateModel(
            name="EmailOutbox",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("to_email", models.EmailField(max_length=254)),
                ("template", models.CharField(max_length=80)),
                ("subject", models.CharField(max_length=255)),
                ("context", models.JSONField(default=dict)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("sending", "Sending"), ("sent", "Sent"), ("failed", "Failed")], default="pending", max_length=20)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("provider_id", models.CharField(blank=True, max_length=255)),
                ("last_error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("is_superuser", models.BooleanField(default=False, help_text="Designates that this user has all permissions without explicitly assigning them.", verbose_name="superuser status")),
                ("id", models.CharField(default=accounts.models.user_id, max_length=32, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("pending_email", models.EmailField(blank=True, max_length=254)),
                ("role", models.CharField(choices=[("Admin", "Admin"), ("Operations", "Operations"), ("Finance", "Finance"), ("Viewer", "Viewer")], default="Viewer", max_length=20)),
                ("status", models.CharField(choices=[("invited", "Invited"), ("active", "Active"), ("suspended", "Suspended"), ("removed", "Removed")], default="invited", max_length=20)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("mfa_secret", models.TextField(blank=True)),
                ("mfa_enabled_at", models.DateTimeField(blank=True, null=True)),
                ("mfa_grace_ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("groups", models.ManyToManyField(blank=True, help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.", related_name="user_set", related_query_name="user", to="auth.group", verbose_name="groups")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="users", to="organizations.organization")),
                ("user_permissions", models.ManyToManyField(blank=True, help_text="Specific permissions for this user.", related_name="user_set", related_query_name="user", to="auth.permission", verbose_name="user permissions")),
            ],
            options={"ordering": ("created_at", "id")},
            managers=[("objects", accounts.managers.UserManager())],
        ),
        migrations.CreateModel(
            name="ActionToken",
            fields=[
                ("id", models.CharField(default=accounts.models.token_id, max_length=32, primary_key=True, serialize=False)),
                ("kind", models.CharField(choices=[("verify_email", "Verify email"), ("reset_password", "Reset password"), ("change_email", "Change email")], max_length=30)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="action_tokens", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.CharField(default=accounts.models.invitation_id, max_length=32, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(choices=[("Admin", "Admin"), ("Operations", "Operations"), ("Finance", "Finance"), ("Viewer", "Viewer")], max_length=20)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("revoked", "Revoked"), ("expired", "Expired")], default="pending", max_length=20)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("invited_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sent_invitations", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invitations", to="organizations.organization")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="MFAChallenge",
            fields=[
                ("id", models.CharField(default=accounts.models.challenge_id, max_length=32, primary_key=True, serialize=False)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mfa_challenges", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="MFARecoveryCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code_hash", models.CharField(max_length=128)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recovery_codes", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                ("session_key", models.CharField(max_length=40, primary_key=True, serialize=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("absolute_expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-last_seen_at",)},
        ),
        migrations.AddConstraint(model_name="user", constraint=models.CheckConstraint(condition=models.Q(("role__in", ["Admin", "Operations", "Finance", "Viewer"])), name="accounts_user_valid_role")),
        migrations.AddConstraint(model_name="user", constraint=models.CheckConstraint(condition=models.Q(("status__in", ["invited", "active", "suspended", "removed"])), name="accounts_user_valid_status")),
        migrations.AddIndex(model_name="actiontoken", index=models.Index(fields=["kind", "token_hash"], name="accounts_ac_kind_b9e17b_idx")),
        migrations.AddConstraint(model_name="invitation", constraint=models.UniqueConstraint(condition=models.Q(("status", "pending")), fields=("organization", "email"), name="accounts_one_pending_invitation")),
        migrations.AddIndex(model_name="mfarecoverycode", index=models.Index(fields=["user", "used_at"], name="accounts_mf_user_id_0737c3_idx")),
    ]
