---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Vessel Caller Redis
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  loop:
    - redis-vessel-caller-production.service
    - redis-vessel-caller-staging.service
