# Generated by Django 5.2.16 on 2026-07-26
import billing.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("operations", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.CharField(default=billing.models.invoice_id, max_length=32, primary_key=True, serialize=False)),
                ("invoice_no", models.CharField(max_length=100)),
                ("cargo_type", models.CharField(max_length=20)),
                ("issued_on", models.DateField()),
                ("due_on", models.DateField()),
                ("status", models.CharField(choices=[("unpaid", "Unpaid"), ("paid", "Paid"), ("void", "Void")], default="unpaid", max_length=20)),
                ("dues", models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ("rate", models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("commission_usd", models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ("commission_ngn", models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ("exchange_rate", models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ("void_reason", models.TextField(blank=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("inspection", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="invoice", to="operations.inspection")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="organizations.organization")),
                ("vessel_call", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="operations.vesselcall")),
            ],
            options={"ordering": ("-issued_on", "-created_at")},
        ),
        migrations.CreateModel(
            name="NumberSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=20)),
                ("year", models.PositiveSmallIntegerField()),
                ("value", models.PositiveIntegerField(default=0)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="organizations.organization")),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.CharField(default=billing.models.payment_id, max_length=32, primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator("0.01")])),
                ("paid_on", models.DateField()),
                ("method", models.CharField(max_length=100)),
                ("reference", models.CharField(max_length=255)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reversal_reason", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="billing.invoice")),
                ("recorded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recorded_payments", to=settings.AUTH_USER_MODEL)),
                ("reversed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reversed_payments", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-recorded_at",)},
        ),
        migrations.AddConstraint(model_name="invoice", constraint=models.UniqueConstraint(fields=("organization", "invoice_no"), name="billing_unique_invoice_number")),
        migrations.AddConstraint(model_name="invoice", constraint=models.CheckConstraint(condition=models.Q(("dues__gte", 0)), name="billing_invoice_nonnegative_dues")),
        migrations.AddConstraint(model_name="numbersequence", constraint=models.UniqueConstraint(fields=("organization", "kind", "year"), name="billing_unique_number_sequence")),
        migrations.AddConstraint(model_name="payment", constraint=models.UniqueConstraint(fields=("invoice", "reference"), name="billing_unique_payment_reference")),
        migrations.AddConstraint(model_name="payment", constraint=models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="billing_payment_positive_amount")),
        migrations.AddConstraint(model_name="payment", constraint=models.UniqueConstraint(condition=models.Q(("idempotency_key", ""), _negated=True), fields=("invoice", "idempotency_key"), name="billing_unique_payment_idempotency")),
    ]
