# Generated by Django 5.2.16 on 2026-07-26
import django.core.validators
import django.db.models.deletion
import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.CharField(default=organizations.models.organization_id, max_length=32, primary_key=True, serialize=False)),
                ("registered", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("rc_number", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                ("primary_port", models.CharField(default="Port of Calabar", max_length=255)),
                ("ports", models.JSONField(blank=True, default=list)),
                ("logo_object_key", models.CharField(blank=True, max_length=1024)),
                ("revision", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("name", "id")},
        ),
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name="settings", serialize=False, to="organizations.organization")),
                ("commission_rate", models.DecimalField(decimal_places=4, default="3.5000", max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ("exchange_rate", models.DecimalField(decimal_places=4, default="1600.0000", max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ("government_liquid_rate", models.DecimalField(decimal_places=4, default="1.6800", max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("private_liquid_rate", models.DecimalField(decimal_places=4, default="2.8800", max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("international_liquid_rate", models.DecimalField(decimal_places=4, default="4.2300", max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("dry_dues_rate", models.DecimalField(decimal_places=4, default="2.1700", max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("port_name", models.CharField(default="Port of Calabar", max_length=255)),
                ("terminals", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
