# Generated by Django 5.2.16 on 2026-07-26
import django.core.validators
import django.db.models.deletion
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                ("id", models.CharField(default=operations.models.inspection_id, max_length=32, primary_key=True, serialize=False)),
                ("reference", models.CharField(max_length=100)),
                ("vessel_name", models.CharField(max_length=255)),
                ("cargo_type", models.CharField(choices=[("Liquid", "Liquid"), ("Dry", "Dry")], default="Liquid", max_length=20)),
                ("product", models.CharField(blank=True, max_length=100)),
                ("reconciled_tonnage", models.DecimalField(decimal_places=3, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ("jetty", models.JSONField(blank=True, null=True)),
                ("liquid", models.JSONField(blank=True, null=True)),
                ("dry", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="draft", max_length=20)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                ("version", models.PositiveIntegerField(default=1)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_inspections", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inspections", to="organizations.organization")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="EvidenceAttachment",
            fields=[
                ("id", models.CharField(default=operations.models.evidence_id, max_length=32, primary_key=True, serialize=False)),
                ("object_key", models.CharField(max_length=1024, unique=True)),
                ("file_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveBigIntegerField()),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evidence", to="organizations.organization")),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="uploaded_evidence", to=settings.AUTH_USER_MODEL)),
                ("inspection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence", to="operations.inspection")),
            ],
            options={"ordering": ("created_at",)},
        ),
        migrations.CreateModel(
            name="VesselCall",
            fields=[
                ("id", models.CharField(default=operations.models.call_id, max_length=32, primary_key=True, serialize=False)),
                ("vessel_name", models.CharField(max_length=255)),
                ("reference", models.CharField(max_length=100)),
                ("vessel_type", models.CharField(blank=True, max_length=100)),
                ("flag", models.CharField(blank=True, max_length=100)),
                ("nrt", models.DecimalField(decimal_places=3, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ("eta", models.DateTimeField(blank=True, null=True)),
                ("sailing_eta", models.DateTimeField(blank=True, null=True)),
                ("berth", models.CharField(blank=True, max_length=255)),
                ("berth_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("in-progress", "In progress"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_vessel_calls", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="vessel_calls", to="organizations.organization")),
            ],
            options={"ordering": ("-registered_at",)},
        ),
        migrations.AddField(model_name="inspection", name="vessel_call", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inspections", to="operations.vesselcall")),
        migrations.AddConstraint(model_name="vesselcall", constraint=models.UniqueConstraint(fields=("organization", "reference"), name="operations_unique_rotation")),
        migrations.AddConstraint(model_name="vesselcall", constraint=models.CheckConstraint(condition=models.Q(("nrt__gte", 0)), name="operations_call_nonnegative_nrt")),
        migrations.AddConstraint(model_name="vesselcall", constraint=models.CheckConstraint(condition=models.Q(("status__in", ["pending", "in-progress", "completed", "cancelled"])), name="operations_call_valid_status")),
        migrations.AddConstraint(model_name="inspection", constraint=models.UniqueConstraint(fields=("organization", "reference"), name="operations_unique_inspection_reference")),
        migrations.AddConstraint(model_name="inspection", constraint=models.CheckConstraint(condition=models.Q(("reconciled_tonnage__gte", 0)), name="operations_inspection_nonnegative_tonnage")),
        migrations.AddConstraint(model_name="inspection", constraint=models.UniqueConstraint(condition=models.Q(("idempotency_key", ""), _negated=True), fields=("organization", "idempotency_key"), name="operations_unique_inspection_idempotency")),
    ]
