import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useStore } from "../app/store";
import { useAuth } from "../auth/AuthContext";
import { Icon } from "../components/Icon";
import { EmptyState } from "../components/ui";
import { Link, useNavigate, useParams, useSearchParams } from "../lib/navigation";
import { ApiError, api } from "../lib/api";
import { measurementApi } from "../measurements/api";
import { PlanForm } from "../measurements/PlanForm";
import { ComparisonGrid } from "../measurements/VoyageComparison";
export { ComparisonGrid } from "../measurements/VoyageComparison";
import { ApprovalForm, AssessmentForm, ProposalForm, ReturnForm } from "../measurements/WorkflowForms";
import { ActionForm, ErrorMessage, EvidenceLink, FormField, MeasurementBadge, Section } from "../measurements/shared";
import { cargoLabelForId, cargoScopeLabel, dateLabel, finalizationIssues, latestReconciliation, latestReturns, localDateTime, quantity, reconciliationStale } from "../measurements/helpers";
import type { Assessment, MeasurementPlan, PlanMutation, Reconciliation } from "../measurements/types";
import "../styles/measurements.css";

export function Measurements() {
  const { org, can } = useAuth();
  const [params] = useSearchParams();
  const callId = params.get("callId") ?? undefined;
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("active");
  const plansQuery = useQuery({ queryKey: ["measurement-plans", org?.id, callId], queryFn: () => measurementApi.list(callId) });
  const plans = plansQuery.data?.plans ?? [];
  const rows = plans.filter(plan => {
    const statusMatches = filter === "all" || (filter === "active" ? ["scheduled", "in-progress"].includes(plan.status) : plan.status === filter);
    return statusMatches && `${plan.title} ${plan.vesselName} ${plan.callReference}`.toLowerCase().includes(search.toLowerCase());
  }).sort((a, b) => new Date(a.scheduledAt).getTime() - new Date(b.scheduledAt).getTime());
  return <div className="content-inner measurement-workspace"><div className="page-head"><div><h1>Measurements</h1><p className="desc">Vessel declarations, separate agency readings and the NPA reconciliation sheet.</p></div>{can("measurements.manage") && <Link className="btn btn-primary" to={`/app/measurements/new${callId ? `?callId=${encodeURIComponent(callId)}` : ""}`}><Icon name="plus" size={17} /> Plan measurement</Link>}</div>
    <div className="measurement-metrics"><div><span>Scheduled</span><strong>{plans.filter(plan => plan.status === "scheduled").length}</strong></div><div><span>In progress</span><strong>{plans.filter(plan => plan.status === "in-progress").length}</strong></div><div><span>Reconciled</span><strong>{plans.filter(plan => plan.status === "reconciled").length}</strong></div></div>
    <div className="filter-bar"><div className="search-input"><Icon name="search" size={17} /><input aria-label="Search measurement plans" placeholder="Search vessel or measurement…" value={search} onChange={event => setSearch(event.target.value)} /></div><label className="measurement-filter">Show <select aria-label="Measurement status" value={filter} onChange={event => setFilter(event.target.value)}><option value="active">Active plans</option><option value="all">All plans</option><option value="reconciled">Reconciled</option><option value="cancelled">Cancelled</option></select></label>{callId && <Link className="link-btn" to="/app/measurements">Show all vessel calls</Link>}</div>
    <ErrorMessage error={plansQuery.error} />{plansQuery.isPending ? <div className="measurement-loading" role="status">Loading measurement plans…</div> : rows.length ? <div className="measurement-plan-list">{rows.map(plan => { const submitted = latestReturns(plan).size; return <Link key={plan.id} to={`/app/measurements/${plan.id}`} className="card measurement-plan-card"><div className="measurement-plan-icon"><Icon name="ruler" size={24} /></div><div className="measurement-plan-content"><div className="measurement-section-head"><h2>{plan.title}</h2><MeasurementBadge status={plan.status} /></div><p>{plan.vesselName} <span>· {plan.callReference}</span></p><div className="measurement-plan-meta"><span><Icon name="calendar" size={14} />{dateLabel(plan.scheduledAt)}</span><span><Icon name="mapPin" size={14} />{plan.location}</span><span><Icon name="users" size={14} />{submitted}/{plan.participants.length} returns</span><span>{plan.lines.length} cargo {plan.lines.length === 1 ? "line" : "lines"}</span></div></div><Icon name="chevronRight" size={18} /></Link>; })}</div> : !plansQuery.error && <div className="card"><EmptyState icon="ruler" title="No measurement plans found" body="Create a measurement plan to collect stakeholder figures and reconcile the result." /></div>}
  </div>;
}

export function NewMeasurement() {
  const store = useStore();
  const navigate = useNavigate();
  const client = useQueryClient();
  const [params] = useSearchParams();
  return <div className="content-inner measurement-workspace"><Link className="measurement-back" to="/app/measurements"><Icon name="chevronLeft" size={16} /> Measurements</Link><div className="page-head"><div><h1>Plan a measurement</h1><p className="desc">Select the vessel and cargo type, add its declared quantities, then collect each agency’s readings.</p></div></div><div className="card measurement-form-card"><PlanForm calls={store.calls} callId={params.get("callId") ?? undefined} onCancel={() => navigate("/app/measurements")} onSave={async input => { const { plan } = await measurementApi.create(input); await client.invalidateQueries({ queryKey: ["measurement-plans"] }); store.toast("Measurement plan created"); navigate(`/app/measurements/${plan.id}`); }} /></div></div>;
}

export function MeasurementDetail() {
  const { id = "" } = useParams<{ id: string }>();
  const { org } = useAuth();
  const result = useQuery({ queryKey: ["measurement-plan", org?.id, id], queryFn: () => measurementApi.detail(id), refetchInterval: 30_000 });
  if (result.isPending) return <div className="measurement-loading" role="status">Loading measurement…</div>;
  if (result.error || !result.data) return <div className="content-inner"><Link to="/app/measurements">Back to measurements</Link><ErrorMessage error={result.error} /></div>;
  return <MeasurementWorkspace key={id} plan={result.data.plan} />;
}

type WorkspaceTab = "overview" | "returns" | "reconciliation" | "billing" | "history";
type ActiveAction = "return" | "proposal" | "approval" | "assess" | "finalize" | "issue" | "schedule" | "cancel" | null;
function MeasurementWorkspace({ plan }: { plan: MeasurementPlan }) {
  const { can, user, org } = useAuth();
  const { toast } = useStore();
  const client = useQueryClient();
  const [tab, setTab] = useState<WorkspaceTab>("overview");
  const [action, setAction] = useState<ActiveAction>(null);
  const [actionVersion, setActionVersion] = useState(plan.version);
  const returns = latestReturns(plan);
  const final = latestReconciliation(plan, "final");
  const draft = latestReconciliation(plan, "draft");
  const latest = latestReconciliation(plan);
  const latestAssessment = plan.assessments.at(-1);
  const cancelled = plan.status === "cancelled";
  const missingReturns = plan.participants.filter(party => party.requiredSubmission && !returns.has(party.id));
  const canManage = can("measurements.manage") && !cancelled;
  const billingReady = Boolean(final && !draft && !cancelled);
  const finalizeIssues = draft ? finalizationIssues(plan, draft, user?.id) : [];
  const save = async (promise: Promise<PlanMutation>, message: string) => {
    try {
      const result = await promise;
      client.setQueryData(["measurement-plan", org?.id, plan.id], { plan: result.plan });
      void client.invalidateQueries({ queryKey: ["measurement-plans"] });
      setAction(null); toast(message);
      return result;
    } catch (error) {
      if (error instanceof ApiError && error.status === 409) await client.invalidateQueries({ queryKey: ["measurement-plan", org?.id, plan.id] });
      throw error;
    }
  };
  const openAction = (next: ActiveAction) => { setActionVersion(plan.version); setAction(next); };
  const close = () => setAction(null);
  const tabs: [WorkspaceTab, string][] = [["overview", "Vessel & cargo"], ["returns", "Agency readings"], ["reconciliation", "Reconciliation"], ["billing", "Disparity billing"], ["history", "Documents & history"]];
  const progress = draft ? 2 : final ? 3 : returns.size ? 1 : 0;
  return <div className="content-inner measurement-workspace"><Link className="measurement-back" to="/app/measurements"><Icon name="chevronLeft" size={16} /> Measurements</Link><div className="page-head"><div><div className="measurement-title"><h1>{plan.title}</h1><MeasurementBadge status={plan.status} /></div><p className="desc"><Link to={`/app/vessel-calls/${plan.callId}`}>{plan.vesselName} · {plan.callReference}</Link> <span> / {plan.scope}</span></p></div><div className="measurement-inline-actions">{canManage && <button className="btn btn-secondary" onClick={() => openAction("schedule")}><Icon name="calendar" size={16} /> Edit schedule</button>}{final && <a className="btn btn-secondary" target="_blank" rel="noopener noreferrer" href={measurementApi.documentUrl(plan.id, final.id)}><Icon name="download" size={16} /> Final sheet v{final.revision}</a>}</div></div>
    <ol className="measurement-progress" aria-label="Measurement progress">{["Vessel & cargo", "Agency readings", "NPA reconciliation", "Final tally & billing"].map((label, index) => <li key={label} className={index <= progress ? "reached" : ""}><span>{index < progress ? <Icon name="check" size={14} /> : index + 1}</span>{label}</li>)}</ol>
    <div className="measurement-tabs" role="tablist" aria-label="Measurement workspaces">{tabs.map(([key, label]) => <button key={key} id={`measurement-tab-${key}`} role="tab" type="button" aria-selected={tab === key} aria-controls="measurement-panel" onClick={() => { setTab(key); setAction(null); }}>{label}{key === "returns" && <span>{returns.size}/{plan.participants.length}</span>}</button>)}</div>
    {action && <Section key={`${action}-${actionVersion}`} title={{ return: "Record received return", proposal: "Propose reconciled quantities", approval: "Record stakeholder acknowledgement", assess: "Assess disparity", finalize: "Finalize reconciliation", issue: "Issue disparity invoice", schedule: "Update measurement schedule", cancel: "Cancel measurement plan" }[action]} action={<button type="button" className="icon-btn" aria-label="Close action" onClick={close}><Icon name="x" size={18} /></button>}>
      {actionVersion !== plan.version && <div className="measurement-notice warning" role="alert">This plan changed while the action was open. Close the action, review the current record and reopen it before saving.</div>}
      {action === "return" && <ReturnForm plan={plan} onCancel={close} onSave={input => save(measurementApi.submit(plan.id, actionVersion, input), "Stakeholder return recorded")} />}
      {action === "proposal" && <ProposalForm plan={plan} onCancel={close} onSave={input => save(measurementApi.propose(plan.id, actionVersion, input), "Reconciliation proposal saved")} />}
      {action === "approval" && draft && <ApprovalForm plan={plan} reconciliation={draft} onCancel={close} onSave={input => save(measurementApi.acknowledge(plan.id, draft.id, actionVersion, input), "Paper acknowledgement recorded")} />}
      {action === "assess" && final && <AssessmentForm plan={plan} reconciliation={final} onCancel={close} onSave={input => save(measurementApi.assess(plan.id, actionVersion, input), "Disparity assessment saved")} />}
      {action === "finalize" && draft && <ActionForm submit={`Finalize version ${draft.revision}`} onCancel={close} disabled={Boolean(finalizeIssues.length)} onSubmit={() => save(measurementApi.finalize(plan.id, draft.id, actionVersion), "Final reconciliation recorded")}><p>You are approving reconciliation v{draft.revision} prepared by {draft.createdBy.name}. This preserves the agreed quantities, exact returns and acknowledgements as a final record. Later corrections require a new version.</p><ComparisonGrid plan={plan} reconciliation={draft} /><GateIssues issues={finalizeIssues} /></ActionForm>}
      {action === "issue" && latestAssessment && <ActionForm submit="Issue invoice" onCancel={close} disabled={!billingReady || latestAssessment.status !== "ready" || latestAssessment.superseded} onSubmit={() => save(measurementApi.issue(plan.id, latestAssessment.id, actionVersion), "Disparity invoice issued")}><p>Issue a USD {quantity(latestAssessment.total)} disparity invoice to <strong>{latestAssessment.payer}</strong> against final reconciliation v{final?.revision}. The assessment already deducts recorded prior charges for this scope.</p><AssessmentTable assessment={latestAssessment} /></ActionForm>}
      {(action === "schedule" || action === "cancel") && <ScheduleForm key={action} plan={plan} cancellation={action === "cancel"} onCancel={close} onSave={input => save(measurementApi.update(plan.id, { ...input, version: actionVersion }), action === "cancel" ? "Measurement plan cancelled" : "Schedule updated")} />}
    </Section>}
    <div id="measurement-panel" role="tabpanel" aria-labelledby={`measurement-tab-${tab}`}>
      {tab === "overview" && <><Section title="Vessel & voyage" description="The vessel and cargo scope shared by all participating agencies."><dl className="measurement-facts">{[["Vessel", plan.vesselName], ["Rotation / call reference", plan.callReference], ["Cargo types", [...new Set(plan.lines.map(line => line.category === "Liquid" ? "Tanker / liquid" : line.category))].join(", ")], ["Scheduled start", dateLabel(plan.scheduledAt)], ["Scheduled end", dateLabel(plan.endsAt)], ["Terminal / berth", plan.location], ["Lead surveyor", plan.leadSurveyor], ["Method", plan.method], ["Operation stage", plan.stage], ["Cargo scope", plan.scope]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || "—"}</dd></div>)}</dl>{plan.notes && <p className="measurement-notes">{plan.notes}</p>}</Section><Section title="Cargo scope"><div className="measurement-table-wrap"><table className="measurement-table"><thead><tr><th>Cargo line</th><th>Direction / category</th><th>Unit & basis</th><th>Vessel declaration</th><th>Declaration reference</th></tr></thead><tbody>{plan.lines.map(line => <tr key={line.id}><th>{line.description}{line.containerSize && <small>{line.containerSize} ft · {line.loadStatus}</small>}</th><td>{line.direction} · {line.category}</td><td>{line.unit}<small>{line.basis}</small></td><td>{quantity(line.manifestQuantity)}</td><td>{line.baselineReference || "Not provided"}</td></tr>)}</tbody></table></div></Section><Section title="Participating agencies" action={canManage && (!final || draft) ? <button className="btn btn-primary" onClick={() => { setTab("returns"); openAction("return"); }}>Record return</button> : undefined}><div className="measurement-party-grid">{plan.participants.map(party => <div key={party.id} className="measurement-party"><div><h3>{party.name}</h3><p>{party.role} · {party.representative}</p><small>{party.requiredSubmission ? "Return required" : "Return optional"} · {party.requiredApproval ? "Agreement required" : "Agreement optional"}</small></div><MeasurementBadge status={returns.has(party.id) ? "received" : "awaiting"} /></div>)}</div></Section>{canManage && !final && <button className="link-btn measurement-danger" onClick={() => openAction("cancel")}>Cancel measurement plan</button>}</>}
      {tab === "returns" && <><Section title="Agency readings & vessel declaration" description="Each agency has a separate column. NPA reviews these readings and records the reconciled tally for each cargo row." action={canManage && (!final || draft) ? <button className="btn btn-primary" onClick={() => openAction("return")}><Icon name="plus" size={16} /> Record return</button> : undefined}><ComparisonGrid plan={plan} reconciliation={latest} />{final && !draft && <div className="measurement-notice">The final result is locked. Start an amendment from Reconciliation before recording revised returns.</div>}</Section><Section title="Agency submission status" description="Each reading retains its reporting agency, the signed-in user who entered it and its supporting documents.">{plan.participants.map(party => { const submission = returns.get(party.id); return <div key={party.id} className="measurement-return"><div><h3>{party.name}<span>{party.role}</span></h3><p>{submission ? `${submission.sourceReference} · Observed ${dateLabel(submission.observedAt)}` : "No return received"}</p>{submission && <small>Recorded by {submission.recordedBy.name} · {dateLabel(submission.recordedAt)}</small>}</div><MeasurementBadge status={submission ? `revision ${submission.revision}` : "awaiting"} /></div>; })}</Section></>}
      {tab === "reconciliation" && <><Section title={draft ? `Reconciliation proposal v${draft.revision}` : final ? `Final reconciliation v${final.revision}` : "NPA reconciliation"} description={draft ? `Prepared by ${draft.createdBy.name} · ${dateLabel(draft.createdAt)}` : final ? `Finalized by ${final.finalizedBy?.name ?? "Admin"} · ${dateLabel(final.finalizedAt)}` : "Compare what the vessel declared with each agency’s measured quantity, then record a justified reconciled tally for every cargo row."} action={canManage ? <button className="btn btn-secondary" disabled={Boolean(missingReturns.length)} onClick={() => openAction("proposal")}>{final && !draft ? "Start amendment" : draft ? "Create revised proposal" : "Propose reconciliation"}</button> : undefined}>
        <GateIssues issues={missingReturns.map(party => `${party.name}: required return missing.`)} />{latest ? <><p className="measurement-notes">{latest.reason}</p><ComparisonGrid plan={plan} reconciliation={draft ?? final ?? latest} />{(draft ?? final ?? latest).lines.map(line => <p className="measurement-decision" key={line.lineId}><strong>{cargoLabelForId(plan.lines, line.lineId)}:</strong> {line.reason}</p>)}</> : <ComparisonGrid plan={plan} />}
      </Section>{(draft ?? final) && <Section title="Agreements & final approval" description="Signed-paper acknowledgements are tied to this exact reconciliation version." action={draft && canManage ? <button className="btn btn-secondary" disabled={reconciliationStale(plan, draft)} onClick={() => openAction("approval")}>Record acknowledgement</button> : undefined}><Acknowledgements plan={plan} reconciliation={(draft ?? final)!} />{draft && <><GateIssues issues={finalizeIssues} />{can("measurements.approve") && <div className="measurement-actions"><button className="btn btn-primary" disabled={Boolean(finalizeIssues.length) || cancelled} onClick={() => openAction("finalize")}><Icon name="check" size={17} /> Review & finalize v{draft.revision}</button></div>}</>}</Section>}</>}
      {tab === "billing" && <><Section title="Disparity assessment" description="Finance chooses an explicit billing policy and verifies previous charges before issuing an additional invoice." action={can("measurements.bill") ? <button className="btn btn-primary" disabled={!billingReady} onClick={() => openAction("assess")}><Icon name="gauge" size={16} /> Assess disparity</button> : undefined}>{!billingReady && <div className="measurement-notice">{draft ? "A new reconciliation proposal is unresolved. Finalize it before assessing or issuing further charges." : "A final approved reconciliation is required before disparity can be assessed."}</div>}{latestAssessment ? <AssessmentView plan={plan} assessment={latestAssessment} canIssue={can("measurements.bill") && billingReady} onIssue={() => openAction("issue")} /> : <EmptyState icon="receipt" title="No disparity assessment yet" body="The approved result is assessed separately. Reconciliation alone does not create an invoice." />}</Section></>}
      {tab === "history" && <><Section title="Supporting documents" description="Private source files retained with the measurement record.">{plan.evidence.length ? plan.evidence.map(evidence => <EvidenceLink key={evidence.id} planId={plan.id} evidence={evidence} />) : <p className="measurement-help">No evidence files uploaded yet.</p>}</Section><Section title="Reconciliation versions">{[...plan.reconciliations].sort((a, b) => b.revision - a.revision).map(recon => <details className="measurement-history" key={recon.id}><summary><strong>Version {recon.revision}</strong><MeasurementBadge status={recon.status} /><span>{dateLabel(recon.createdAt)}</span></summary><p>{recon.reason}</p><p className="measurement-help">Prepared by {recon.createdBy.name}{recon.finalizedBy ? ` · Finalized by ${recon.finalizedBy.name} on ${dateLabel(recon.finalizedAt)}` : ""}</p><ComparisonGrid plan={plan} reconciliation={recon} snapshot /><Acknowledgements plan={plan} reconciliation={recon} /><a href={measurementApi.documentUrl(plan.id, recon.id)} className="link-btn" target="_blank" rel="noopener noreferrer">Download version {recon.revision} sheet</a></details>)}{!plan.reconciliations.length && <p className="measurement-help">No reconciliation versions yet.</p>}</Section><Section title="Submission history">{[...plan.submissions].sort((a, b) => b.recordedAt.localeCompare(a.recordedAt)).map(submission => <details className="measurement-history" key={submission.id}><summary><strong>{plan.participants.find(party => party.id === submission.participantId)?.name}</strong><span>Revision {submission.revision}</span><span>{dateLabel(submission.recordedAt)}</span></summary><p>Source: {submission.sourceReference} · Recorded by {submission.recordedBy.name}</p>{submission.reason && <p>Revision reason: {submission.reason}</p>}{submission.notes && <p>{submission.notes}</p>}<ul>{submission.lines.map(line => <li key={line.lineId}>{cargoLabelForId(plan.lines, line.lineId)}: {line.status === "not-applicable" ? "Not applicable" : quantity(line.quantity)}{line.note && ` · ${line.note}`}</li>)}</ul>{submission.evidenceIds.map(id => { const evidence = plan.evidence.find(item => item.id === id); return evidence ? <EvidenceLink key={id} planId={plan.id} evidence={evidence} /> : null; })}</details>)}{!plan.submissions.length && <p className="measurement-help">No returns recorded yet.</p>}</Section><Section title="Assessment history">{[...plan.assessments].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(assessment => <details className="measurement-history" key={assessment.id}><summary><strong>USD {quantity(assessment.total)}</strong><MeasurementBadge status={assessment.superseded ? "superseded" : assessment.status} /><span>{dateLabel(assessment.createdAt)}</span></summary><AssessmentView plan={plan} assessment={assessment} canIssue={false} onIssue={() => {}} /></details>)}</Section></>}
    </div>
  </div>;
}

function GateIssues({ issues }: { issues: string[] }) {
  return issues.length ? <div className="measurement-notice warning"><ul>{issues.map(issue => <li key={issue}>{issue}</li>)}</ul></div> : null;
}

function Acknowledgements({ plan, reconciliation }: { plan: MeasurementPlan; reconciliation: Reconciliation }) {
  const approvals = new Map(reconciliation.approvals.map(approval => [approval.participantId, approval]));
  return <div>{plan.participants.map(party => { const approval = approvals.get(party.id); return <div className="measurement-return" key={party.id}><div><h3>{party.name}</h3><p>{approval ? `${approval.representative} · ${approval.reference}` : party.requiredApproval ? "Required agreement pending" : "Optional agreement"}</p>{approval && <small>Paper acknowledgement recorded by {approval.recordedBy.name} · {dateLabel(approval.recordedAt)}</small>}</div><MeasurementBadge status={approval?.decision ?? "awaiting"} /></div>; })}</div>;
}
function AssessmentView({ plan, assessment, canIssue, onIssue }: { plan: MeasurementPlan; assessment: Assessment; canIssue: boolean; onIssue: () => void }) {
  const recon = plan.reconciliations.find(item => item.id === assessment.reconciliationId);
  return <><div className="measurement-assessment-heading"><div><MeasurementBadge status={assessment.superseded ? "superseded" : assessment.status} /><h3>{assessment.payer}</h3><p>{assessment.policy === "manifest-disparity" ? "Excess over manifest" : "Adjustment above previously billed quantity"} · Final v{recon?.revision ?? "—"} · {assessment.tariffReference}</p></div><div className="measurement-assessment-total"><span>Additional charge · USD</span><strong>{quantity(assessment.total)}</strong></div></div><AssessmentTable assessment={assessment} /><p className="measurement-help">Opening position: {assessment.openingChargesReference} · {assessment.reason}</p>{assessment.status === "held" && <div className="measurement-notice warning">This assessment is held for credit or adjustment review. No invoice can be issued. Review the line amounts and prior charges.</div>}{assessment.status === "no-charge" && <div className="measurement-notice">No additional charge is due. This assessment is retained with the final result.</div>}<div className="measurement-actions">{assessment.invoiceId ? <><Link className="btn btn-secondary" to={`/app/invoices?focus=${encodeURIComponent(assessment.invoiceId)}`}>View invoice</Link><a className="btn btn-secondary" href={api.invoicePdfUrl(assessment.invoiceId)} target="_blank" rel="noopener noreferrer"><Icon name="download" size={16} /> Invoice PDF</a></> : canIssue && !assessment.superseded && assessment.status === "ready" && <button className="btn btn-primary" onClick={onIssue}>Review & issue invoice</button>}</div></>;
}
function AssessmentTable({ assessment }: { assessment: Assessment }) {
  return <div className="measurement-table-wrap"><table className="measurement-table"><thead><tr><th>Cargo line</th><th>Baseline</th><th>Final</th><th>Variance</th><th>Tolerance</th><th>Chargeable</th><th>USD rate</th><th>Entitlement</th><th>Opening</th><th>Prior invoiced</th><th>Net USD</th></tr></thead><tbody>{assessment.lines.map(line => <tr key={line.lineId}><th>{line.description}<small>{[line.unit, cargoScopeLabel(line), line.basis].filter(Boolean).join(" · ")}</small></th><td>{quantity(line.baselineQuantity)}</td><td>{quantity(line.finalQuantity)}</td><td>{quantity(line.variance)}</td><td>{quantity(line.tolerance)}<small>{line.toleranceMode}</small></td><td>{quantity(line.chargeableQuantity)}</td><td>{quantity(line.rate)}</td><td>{quantity(line.entitlement)}</td><td>{quantity(line.openingBilledAmount)}</td><td>{quantity(line.priorInvoicedAmount)}</td><td><strong>{quantity(line.amount)}</strong></td></tr>)}</tbody></table></div>;
}
function ScheduleForm({ plan, cancellation, onSave, onCancel }: { plan: MeasurementPlan; cancellation: boolean; onSave: (input: { title?: string; scheduledAt?: string; endsAt?: string | null; location?: string; leadSurveyor?: string; notes?: string; status?: "cancelled"; reason?: string }) => Promise<unknown>; onCancel: () => void }) {
  const [details, setDetails] = useState({ title: plan.title, scheduledAt: localDateTime(plan.scheduledAt), endsAt: plan.endsAt ? localDateTime(plan.endsAt) : "", location: plan.location, leadSurveyor: plan.leadSurveyor, notes: plan.notes });
  const [reason, setReason] = useState("");
  return <ActionForm submit={cancellation ? "Cancel measurement plan" : "Save schedule"} onCancel={onCancel} onSubmit={() => onSave(cancellation ? { status: "cancelled", reason } : { ...details, scheduledAt: new Date(details.scheduledAt).toISOString(), endsAt: details.endsAt ? new Date(details.endsAt).toISOString() : null })}>{cancellation ? <FormField label="Cancellation reason"><textarea required value={reason} onChange={event => setReason(event.target.value)} /></FormField> : <div className="measurement-form-grid">{([['title', 'Plan title'], ['location', 'Terminal / berth'], ['leadSurveyor', 'Lead surveyor']] as const).map(([key, label]) => <FormField key={key} label={label}><input required value={details[key]} onChange={event => setDetails({ ...details, [key]: event.target.value })} /></FormField>)}<FormField label="Scheduled start"><input required type="datetime-local" value={details.scheduledAt} onChange={event => setDetails({ ...details, scheduledAt: event.target.value })} /></FormField><FormField label="Scheduled end (optional)"><input type="datetime-local" min={details.scheduledAt} value={details.endsAt} onChange={event => setDetails({ ...details, endsAt: event.target.value })} /></FormField><FormField label="Planning notes"><textarea value={details.notes} onChange={event => setDetails({ ...details, notes: event.target.value })} /></FormField></div>}</ActionForm>;
}
