import { useState } from "react";
import type { VesselCall } from "../types";
import { Icon } from "../components/Icon";
import { ActionForm, FormField } from "./shared";
import { localDateTime } from "./helpers";
import type { CargoLineInput, ParticipantInput, PlanInput, QuantityUnit } from "./types";

const blankLine = (): CargoLineInput => ({ description: "", category: "Bulk", direction: "import", containerSize: "", loadStatus: "", unit: "tonnes", basis: "", manifestQuantity: null, baselineReference: "" });
const blankParty = (): ParticipantInput => ({ name: "", role: "Agent", representative: "", requiredSubmission: true, requiredApproval: true });
export function PlanForm({ calls, callId: initialCallId, onSave, onCancel }: { calls: VesselCall[]; callId?: string; onSave: (value: PlanInput) => Promise<unknown>; onCancel: () => void }) {
  const [callId, setCallId] = useState(initialCallId ?? "");
  const [details, setDetails] = useState({ title: "", scheduledAt: localDateTime(), endsAt: "", location: "", method: "", stage: "", scope: "", leadSurveyor: "", notes: "" });
  const [lines, setLines] = useState<CargoLineInput[]>([blankLine()]);
  const [participants, setParticipants] = useState<ParticipantInput[]>([blankParty()]);
  const updateLine = (index: number, patch: Partial<CargoLineInput>) => setLines(current => current.map((line, i) => i === index ? { ...line, ...patch } : line));
  const updateParty = (index: number, patch: Partial<ParticipantInput>) => setParticipants(current => current.map((party, i) => i === index ? { ...party, ...patch } : party));
  return <ActionForm submit="Create measurement plan" onCancel={onCancel} onSubmit={() => onSave({ ...details, callId, scheduledAt: new Date(details.scheduledAt).toISOString(), endsAt: details.endsAt ? new Date(details.endsAt).toISOString() : null, lines, participants })}>
    <h2>Schedule & scope</h2><p className="measurement-help">Define a distinct cargo parcel and operation stage for this measurement.</p>
    <div className="measurement-form-grid"><FormField label="Vessel call"><select required value={callId} onChange={event => setCallId(event.target.value)}><option value="">Select a vessel call</option>{calls.filter(call => call.status !== "cancelled").map(call => <option value={call.id} key={call.id}>{call.vesselName} · {call.reference}</option>)}</select></FormField><FormField label="Plan title"><input required value={details.title} onChange={event => setDetails({ ...details, title: event.target.value })} placeholder="Discharge tally · Parcel A" /></FormField>
      <FormField label="Scheduled start" hint="Dates use your local time zone."><input required type="datetime-local" value={details.scheduledAt} onChange={event => setDetails({ ...details, scheduledAt: event.target.value })} /></FormField><FormField label="Scheduled end (optional)"><input type="datetime-local" min={details.scheduledAt} value={details.endsAt} onChange={event => setDetails({ ...details, endsAt: event.target.value })} /></FormField>
      {([['location', 'Terminal / berth'], ['leadSurveyor', 'Lead surveyor'], ['method', 'Measurement method'], ['stage', 'Operation stage'], ['scope', 'Parcel / cargo scope']] as const).map(([key, label]) => <FormField key={key} label={label}><input required value={details[key]} onChange={event => setDetails({ ...details, [key]: event.target.value })} /></FormField>)}
      <FormField label="Planning notes (optional)"><textarea value={details.notes} onChange={event => setDetails({ ...details, notes: event.target.value })} /></FormField></div>
    <div className="measurement-section-head"><div><h2>Cargo lines</h2><p>Each line has one unit and quantity basis. Keep container sizes and loading states separate.</p></div><button className="btn btn-secondary" type="button" onClick={() => setLines(current => [...current, blankLine()])}><Icon name="plus" size={16} /> Add cargo line</button></div>
    {lines.map((line, index) => <div className="measurement-editor-row" key={index}><div className="measurement-section-head"><h3>Cargo line {index + 1}</h3>{lines.length > 1 && <button type="button" className="icon-btn" aria-label={`Remove cargo line ${index + 1}`} onClick={() => setLines(current => current.filter((_, i) => i !== index))}><Icon name="trash" size={17} /></button>}</div><div className="measurement-form-grid">
      <FormField label={`Cargo description ${index + 1}`}><input required value={line.description} onChange={event => updateLine(index, { description: event.target.value })} /></FormField>
      <FormField label={`Category ${index + 1}`}><select value={line.category} onChange={event => updateLine(index, { category: event.target.value, unit: event.target.value === "Container" || event.target.value === "Vehicle" ? "count" : "tonnes" })}>{["Bulk", "Liquid", "Container", "Vehicle", "General cargo"].map(category => <option key={category}>{category}</option>)}</select></FormField>
      <FormField label={`Direction ${index + 1}`}><select value={line.direction} onChange={event => updateLine(index, { direction: event.target.value })}><option value="import">Import / discharge</option><option value="export">Export / loading</option></select></FormField>
      <FormField label={`Unit ${index + 1}`}><select value={line.unit} onChange={event => updateLine(index, { unit: event.target.value as QuantityUnit })}><option value="tonnes">Tonnes</option><option value="count">Count</option><option value="m3">Cubic metres (m³)</option></select></FormField>
      {line.category === "Container" && <><FormField label={`Container size ${index + 1}`}><select required value={line.containerSize} onChange={event => updateLine(index, { containerSize: event.target.value })}><option value="">Select size</option>{["20", "40", "45"].map(size => <option key={size} value={size}>{size} ft</option>)}</select></FormField><FormField label={`Load status ${index + 1}`}><select required value={line.loadStatus} onChange={event => updateLine(index, { loadStatus: event.target.value })}><option value="">Select status</option><option value="laden">Laden</option><option value="empty">Empty</option></select></FormField></>}
      <FormField label={`Quantity basis ${index + 1}`}><input required value={line.basis} placeholder="Net metric tonnes / physical container count" onChange={event => updateLine(index, { basis: event.target.value })} /></FormField>
      <FormField label={`Manifest quantity ${index + 1}`} hint="Leave blank if unknown. Zero means an explicit NIL declaration."><input type="number" min="0" step={line.unit === "count" ? "1" : "0.001"} value={line.manifestQuantity ?? ""} onChange={event => updateLine(index, { manifestQuantity: event.target.value === "" ? null : event.target.value })} /></FormField>
      <FormField label={`Manifest / baseline reference ${index + 1}`}><input required={line.manifestQuantity !== null} value={line.baselineReference} onChange={event => updateLine(index, { baselineReference: event.target.value })} /></FormField></div></div>)}
    <div className="measurement-section-head"><div><h2>Participating stakeholders</h2><p>Staff will record received returns and signed agreements on behalf of each named party.</p></div><button className="btn btn-secondary" type="button" onClick={() => setParticipants(current => [...current, blankParty()])}><Icon name="plus" size={16} /> Add stakeholder</button></div>
    {participants.map((party, index) => <div className="measurement-editor-row" key={index}><div className="measurement-section-head"><h3>Stakeholder {index + 1}</h3>{participants.length > 1 && <button type="button" className="icon-btn" aria-label={`Remove stakeholder ${index + 1}`} onClick={() => setParticipants(current => current.filter((_, i) => i !== index))}><Icon name="trash" size={17} /></button>}</div><div className="measurement-form-grid"><FormField label={`Party name ${index + 1}`}><input required value={party.name} onChange={event => updateParty(index, { name: event.target.value })} /></FormField><FormField label={`Role ${index + 1}`}><input required list="measurement-party-roles" value={party.role} onChange={event => updateParty(index, { role: event.target.value })} /></FormField><FormField label={`Representative ${index + 1}`}><input required value={party.representative} onChange={event => updateParty(index, { representative: event.target.value })} /></FormField><div className="measurement-checkbox-stack"><label className="measurement-check"><input type="checkbox" checked={party.requiredSubmission} onChange={event => updateParty(index, { requiredSubmission: event.target.checked })} /> Return required</label><label className="measurement-check"><input type="checkbox" checked={party.requiredApproval} onChange={event => updateParty(index, { requiredApproval: event.target.checked })} /> Agreement required</label></div></div></div>)}
    <datalist id="measurement-party-roles">{["Agent", "Terminal operator", "Master", "Surveyor", "Tally clerk"].map(role => <option key={role} value={role} />)}</datalist>
  </ActionForm>;
}
